import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFrontMatter, renderBody, rewriteImages, buildBundle } from "./build-docs-lib.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = join(HERE, "..", "..", "docs", "guide");
const IMAGES = join(WEB, "images");
const OUT = join(HERE, "..", "src", "editor", "help", "generated");
const SECTION_ORDER = ["Getting Started", "Building Rules", "Administering", "Developer Reference"];

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const p = join(dir, e.name);
    if (e.isDirectory()) return walk(p);
    return e.name.endsWith(".md") && e.name !== "manifest.md" && e.name !== "_page-template.md" ? [p] : [];
  });
}

const pages = [];
for (const file of walk(WEB)) {
  const { meta, body } = parseFrontMatter(readFileSync(file, "utf8"));
  let html = rewriteImages(renderBody(body));
  // fail on missing referenced image
  for (const ref of [...html.matchAll(/src="asx_\/docs\/images\/([^"]+)"/g)]) {
    if (!existsSync(join(IMAGES, ref[1]))) throw new Error(`${meta.slug}: missing image ${ref[1]}`);
  }
  pages.push({ meta, html });
}

const bundle = buildBundle(pages, SECTION_ORDER);
mkdirSync(OUT, { recursive: true });
writeFileSync(
  join(OUT, "docs.ts"),
  `// GENERATED by client/scripts/build-docs.mjs. Do not edit.\nimport type { DocsBundle } from "../types";\nexport const DOCS: DocsBundle = ${JSON.stringify(bundle)};\n`,
  "utf8"
);
console.log(`build-docs: ${pages.length} pages → src/editor/help/generated/docs.ts`);
