import { makeStyles, tokens, shorthands } from "@fluentui/react-components";
import { color } from "../ui/tokens";

// The in-app docs viewer (HelpApp/DocNav/DocPage), styled after the product website's docs
// pages: a dark header band, a carded contents sidebar, and the page on a white card with
// captioned screenshots that open full size. One column below 860px, where the contents fold
// behind a toggle; tighter padding below 720px.
const NARROW = "@media (max-width: 860px)";
const SMALL = "@media (max-width: 720px)";

export const useHelpStyles = makeStyles({
  shell: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    backgroundColor: color.canvas,
    fontFamily: tokens.fontFamilyBase,
    color: color.ink,
  },

  // ---- Header band ----
  hero: {
    backgroundImage: `linear-gradient(160deg, ${color.docsHero}, ${color.docsHeroEnd})`,
    color: color.surface,
    ...shorthands.padding("26px", "32px", "24px"),
    [SMALL]: { ...shorthands.padding("20px", "20px", "18px") },
  },
  heroInner: { maxWidth: "1200px", margin: "0 auto" },
  heroTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    ...shorthands.gap("8px", "16px"),
  },
  crumbs: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    ...shorthands.gap("8px"),
    fontSize: "13.5px",
    color: color.docsHeroInk,
  },
  crumbLink: {
    color: color.docsHeroInk,
    backgroundColor: "transparent",
    ...shorthands.border("none"),
    ...shorthands.padding("0"),
    font: "inherit",
    cursor: "pointer",
    ":hover": { color: color.surface, textDecorationLine: "underline" },
    ":focus-visible": { outline: `2px solid ${color.brandOnInk}`, outlineOffset: "2px" },
  },
  crumbCurrent: { color: color.surface },
  heroTitleRow: { display: "flex", alignItems: "center", flexWrap: "wrap", ...shorthands.gap("12px"), marginTop: "14px" },
  heroTitle: {
    margin: 0,
    fontSize: "28px",
    lineHeight: "1.15",
    fontWeight: 700,
    letterSpacing: "-0.5px",
    color: color.surface,
    [SMALL]: { fontSize: "23px" },
  },
  pill: {
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("4px", "12px"),
    ...shorthands.borderRadius("999px"),
    ...shorthands.border("1px", "solid", color.brandOnInk),
    fontSize: "12.5px",
    fontWeight: 600,
    color: color.brandOnInk,
  },
  heroLink: {
    display: "inline-flex",
    alignItems: "center",
    ...shorthands.padding("6px", "13px"),
    ...shorthands.borderRadius("999px"),
    ...shorthands.border("1px", "solid", color.docsHeroInk),
    fontSize: "12.5px",
    fontWeight: 600,
    color: color.surface,
    textDecorationLine: "none",
    ":hover": { backgroundColor: color.docsHeroEnd },
    ":focus-visible": { outline: `2px solid ${color.brandOnInk}`, outlineOffset: "2px" },
  },

  // ---- Body: contents + page ----
  body: {
    width: "100%",
    maxWidth: "1200px",
    margin: "0 auto",
    boxSizing: "border-box",
    ...shorthands.padding("32px", "32px", "64px"),
    display: "grid",
    gridTemplateColumns: "240px minmax(0, 1fr)",
    ...shorthands.gap("32px"),
    alignItems: "start",
    [NARROW]: { gridTemplateColumns: "minmax(0, 1fr)", ...shorthands.gap("16px") },
    [SMALL]: { ...shorthands.padding("16px", "16px", "48px") },
  },

  nav: {
    position: "sticky",
    top: "16px",
    maxHeight: "calc(100vh - 32px)",
    overflowY: "auto",
    backgroundColor: color.surface,
    ...shorthands.border("1px", "solid", color.line),
    ...shorthands.borderRadius("14px"),
    ...shorthands.padding("16px"),
    // The website hides this scrollbar too: the list still scrolls.
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
    [NARROW]: { position: "static", maxHeight: "none" },
  },
  // Below 860px the contents fold behind this toggle, so the page comes first.
  navToggle: {
    display: "none",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.gap("8px"),
    ...shorthands.padding("2px", "0"),
    backgroundColor: "transparent",
    ...shorthands.border("none"),
    font: "inherit",
    fontSize: "14px",
    fontWeight: 600,
    color: color.ink,
    cursor: "pointer",
    textAlign: "left",
    [NARROW]: { display: "flex" },
    ":focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "2px" },
  },
  navToggleCurrent: { flex: 1, minWidth: 0, textAlign: "right", fontWeight: 400, color: color.inkMuted, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  navBody: { marginTop: 0 },
  navBodyFolded: { [NARROW]: { display: "none" } },
  navBodyOpen: { [NARROW]: { marginTop: "12px" } },
  search: {
    width: "100%",
    boxSizing: "border-box",
    ...shorthands.padding("8px", "10px"),
    ...shorthands.border("1px", "solid", color.line),
    ...shorthands.borderRadius("8px"),
    font: "inherit",
    fontSize: "13.5px",
    marginBottom: "12px",
    backgroundColor: color.surface,
    color: color.ink,
    ":focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "1px" },
  },
  secHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    ...shorthands.padding("4px", "0"),
    ...shorthands.border("none"),
    backgroundColor: "transparent",
    font: "inherit",
    fontSize: "11.5px",
    fontWeight: 700,
    letterSpacing: "1.1px",
    textTransform: "uppercase",
    color: color.inkMuted,
    cursor: "pointer",
    textAlign: "left",
    ":hover": { color: color.ink },
    ":focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "2px" },
  },
  // Space between sections, not above the first.
  section: { "& + &": { marginTop: "14px" } },
  caret: { flexShrink: 0, transitionProperty: "transform", transitionDuration: "0.18s" },
  caretOpen: { transform: "rotate(180deg)" },
  secPages: { display: "flex", flexDirection: "column", ...shorthands.gap("2px"), marginTop: "6px" },
  pageRow: {
    display: "block",
    width: "100%",
    textAlign: "left",
    ...shorthands.padding("7px", "10px"),
    ...shorthands.border("none"),
    ...shorthands.borderRadius("8px"),
    backgroundColor: "transparent",
    font: "inherit",
    fontSize: "14px",
    color: color.inkMuted,
    cursor: "pointer",
    ":hover": { color: color.ink, backgroundColor: color.canvas },
    ":focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "1px" },
  },
  pageRowActive: { color: color.brandInk, fontWeight: 600, backgroundColor: color.brandTint, ":hover": { color: color.brandInk, backgroundColor: color.brandTint } },
  noMatch: { fontSize: "13.5px", color: color.inkMuted, ...shorthands.padding("4px", "2px") },

  // ---- Page card ----
  article: {
    minWidth: 0,
    backgroundColor: color.surface,
    ...shorthands.border("1px", "solid", color.line),
    ...shorthands.borderRadius("18px"),
    ...shorthands.padding("40px", "44px"),
    [SMALL]: { ...shorthands.padding("24px", "20px"), ...shorthands.borderRadius("14px") },
  },
  pageSection: {
    fontSize: "12px",
    fontWeight: 700,
    letterSpacing: "1px",
    textTransform: "uppercase",
    color: color.brandInk,
    marginBottom: "8px",
  },
  title: {
    margin: "0 0 20px",
    fontSize: "30px",
    lineHeight: "1.15",
    fontWeight: 700,
    letterSpacing: "-0.6px",
    color: color.ink,
    [SMALL]: { fontSize: "25px" },
  },
  prose: {
    fontSize: "15.5px",
    lineHeight: "1.72",
    color: color.inkMuted,
    overflowWrap: "break-word",
    "& > :first-child": { marginTop: 0 },
    "& h2": { fontSize: "21px", fontWeight: 700, letterSpacing: "-0.3px", color: color.ink, margin: "34px 0 12px", lineHeight: "1.3" },
    "& h3": { fontSize: "17px", fontWeight: 700, color: color.ink, margin: "26px 0 10px" },
    "& h4": { fontSize: "15.5px", fontWeight: 700, color: color.ink, margin: "22px 0 8px" },
    "& p": { margin: "0 0 16px" },
    "& ul, & ol": { margin: "0 0 16px", paddingLeft: "22px" },
    "& li": { marginBottom: "6px" },
    "& li::marker": { color: color.inkMuted },
    "& strong": { color: color.ink, fontWeight: 700 },
    "& a": { color: color.brandInk, fontWeight: 600 },
    "& code": {
      fontFamily: tokens.fontFamilyMonospace,
      fontSize: "0.88em",
      backgroundColor: color.brandTint,
      color: color.brandInk,
      ...shorthands.padding("2px", "6px"),
      ...shorthands.borderRadius("6px"),
      // Long identifiers wrap instead of pushing the page sideways on a phone.
      overflowWrap: "anywhere",
    },
    "& pre": {
      backgroundColor: color.codeBg,
      color: color.codeInk,
      fontSize: "13.5px",
      lineHeight: "1.65",
      ...shorthands.padding("16px", "18px"),
      ...shorthands.borderRadius("12px"),
      overflowX: "auto",
      margin: "0 0 16px",
    },
    "& pre code": { backgroundColor: "transparent", color: "inherit", ...shorthands.padding("0"), fontSize: "inherit", overflowWrap: "normal" },
    "& blockquote": {
      margin: "0 0 16px",
      ...shorthands.padding("14px", "18px"),
      borderLeft: `3px solid ${color.brand}`,
      backgroundColor: color.canvas,
      ...shorthands.borderRadius("0", "12px", "12px", "0"),
      fontSize: "14.5px",
      lineHeight: "1.6",
    },
    "& blockquote p:last-child": { marginBottom: 0 },
    "& table": { display: "block", overflowX: "auto", width: "100%", borderCollapse: "collapse", margin: "0 0 20px", fontSize: "14px" },
    "& th": { textAlign: "left", backgroundColor: color.canvas, color: color.ink, fontWeight: 600, ...shorthands.padding("9px", "12px"), borderBottom: `1px solid ${color.line}`, whiteSpace: "nowrap" },
    "& td": { ...shorthands.padding("9px", "12px"), borderBottom: `1px solid ${color.line}`, verticalAlign: "top" },
    "& tr:last-child td": { borderBottom: "none" },
    "& img": { display: "block", maxWidth: "100%", height: "auto", ...shorthands.border("1px", "solid", color.line), ...shorthands.borderRadius("12px") },
    "& figure": { margin: "8px 0 26px" },
    "& figcaption": { marginTop: "10px", fontSize: "13.5px", lineHeight: "1.5", color: color.inkMuted },
    "& .doc-zoom": {
      display: "block",
      width: "100%",
      ...shorthands.padding("0"),
      ...shorthands.border("none"),
      backgroundColor: "transparent",
      cursor: "zoom-in",
      ...shorthands.borderRadius("12px"),
    },
    "& .doc-zoom:focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "3px" },
  },

  // ---- Previous / Next ----
  pager: {
    display: "flex",
    justifyContent: "space-between",
    ...shorthands.gap("16px"),
    marginTop: "40px",
    paddingTop: "22px",
    borderTop: `1px solid ${color.line}`,
    [SMALL]: { flexDirection: "column" },
  },
  pagerLink: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("4px"),
    maxWidth: "48%",
    ...shorthands.padding("12px", "16px"),
    ...shorthands.border("1px", "solid", color.line),
    ...shorthands.borderRadius("12px"),
    backgroundColor: color.surface,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
    ":hover": { backgroundColor: color.canvas, ...shorthands.borderColor(color.brandLine) },
    ":focus-visible": { outline: `2px solid ${color.brand}`, outlineOffset: "2px" },
    [SMALL]: { maxWidth: "100%" },
  },
  pagerNext: { marginLeft: "auto", textAlign: "right", alignItems: "flex-end", [SMALL]: { marginLeft: 0, textAlign: "left", alignItems: "flex-start" } },
  pagerDir: { fontSize: "12.5px", fontWeight: 600, color: color.inkMuted },
  pagerTitle: { fontSize: "14.5px", fontWeight: 700, color: color.ink },

  // ---- Full-size screenshot ----
  lightbox: {
    position: "fixed",
    inset: 0,
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ...shorthands.padding("24px"),
    backgroundColor: `${color.docsHero}e6`,
    cursor: "zoom-out",
  },
  lightboxImg: {
    maxWidth: "100%",
    maxHeight: "100%",
    width: "auto",
    height: "auto",
    ...shorthands.borderRadius("12px"),
    backgroundColor: color.surface,
  },
  lightboxClose: {
    position: "fixed",
    top: "14px",
    right: "18px",
    width: "40px",
    height: "40px",
    ...shorthands.border("none"),
    ...shorthands.borderRadius("50%"),
    backgroundColor: color.docsHeroEnd,
    color: color.surface,
    fontSize: "24px",
    lineHeight: 1,
    cursor: "pointer",
    ":focus-visible": { outline: `2px solid ${color.brandOnInk}`, outlineOffset: "2px" },
  },
});
