import { makeStyles, tokens, shorthands } from "@fluentui/react-components";

// Fluent v9 styles for the in-app docs viewer (HelpApp/DocNav/DocPage).
// Two-pane layout: fixed-width nav + reading-width content pane, stacking
// below 820px to match the editor's other responsive breakpoints
// (see TableConfigApp/TableConfigTree useIsWide(820)).
export const useHelpStyles = makeStyles({
  shell: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    backgroundColor: tokens.colorNeutralBackground2,
    fontFamily: tokens.fontFamilyBase,
  },
  head: {
    ...shorthands.padding("28px", "32px", "20px"),
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  headTop: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    flexWrap: "wrap",
    ...shorthands.gap("8px", "16px"),
  },
  headLink: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorBrandForeground1,
    textDecorationLine: "none",
    ":hover": { textDecorationLine: "underline" },
    ":focus-visible": {
      outline: `2px solid ${tokens.colorBrandStroke1}`,
      outlineOffset: "1px",
    },
  },
  eyebrow: {
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: tokens.colorBrandForeground1,
    marginBottom: "4px",
  },
  title: {
    fontSize: tokens.fontSizeHero800,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    margin: "0 0 6px 0",
  },
  subtitle: {
    fontSize: tokens.fontSizeBase400,
    color: tokens.colorNeutralForeground3,
    margin: 0,
    maxWidth: "66ch",
  },
  docs: {
    display: "grid",
    gridTemplateColumns: "258px 1fr",
    ...shorthands.gap("0"),
    flex: "1 1 auto",
    alignItems: "start",
    "@media (max-width: 820px)": {
      gridTemplateColumns: "1fr",
    },
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    ...shorthands.gap("2px"),
    ...shorthands.padding("18px", "14px"),
    borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    position: "sticky",
    top: 0,
    alignSelf: "start",
    maxHeight: "100vh",
    overflowY: "auto",
    "@media (max-width: 820px)": {
      position: "static",
      maxHeight: "none",
      borderRight: "none",
      borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    },
  },
  search: {
    ...shorthands.padding("8px", "10px"),
    ...shorthands.border("1px", "solid", tokens.colorNeutralStroke1),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    fontSize: tokens.fontSizeBase300,
    marginBottom: "10px",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    ":focus-visible": {
      outline: `2px solid ${tokens.colorBrandStroke1}`,
      outlineOffset: "1px",
    },
  },
  secHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    ...shorthands.padding("8px", "8px"),
    ...shorthands.border("none"),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: "transparent",
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: tokens.colorNeutralForeground3,
    cursor: "pointer",
    textAlign: "left",
    marginTop: "10px",
    ":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
  },
  pageRow: {
    display: "block",
    width: "100%",
    textAlign: "left",
    ...shorthands.padding("7px", "10px"),
    ...shorthands.border("none"),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: "transparent",
    fontSize: tokens.fontSizeBase300,
    color: tokens.colorNeutralForeground1,
    cursor: "pointer",
    ":hover": { backgroundColor: tokens.colorNeutralBackground1Hover },
  },
  pageRowActive: {
    display: "block",
    width: "100%",
    textAlign: "left",
    ...shorthands.padding("7px", "10px"),
    ...shorthands.border("none"),
    ...shorthands.borderRadius(tokens.borderRadiusMedium),
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase300,
    cursor: "pointer",
  },
  article: {
    ...shorthands.padding("32px", "40px", "60px"),
    maxWidth: "860px",
  },
  crumbs: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    marginBottom: "10px",
  },
  prose: {
    maxWidth: "66ch",
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase400,
    color: tokens.colorNeutralForeground1,
    "& h1, & h2, & h3, & h4": {
      fontWeight: tokens.fontWeightSemibold,
      color: tokens.colorNeutralForeground1,
      marginTop: "1.6em",
      marginBottom: "0.5em",
    },
    "& p": { marginTop: 0, marginBottom: "1em" },
    "& ul, & ol": {
      paddingLeft: "1.4em",
      marginTop: 0,
      marginBottom: "1em",
    },
    "& li": { marginBottom: "0.35em" },
    "& code": {
      fontFamily: tokens.fontFamilyMonospace,
      fontSize: "0.92em",
      backgroundColor: tokens.colorNeutralBackground3,
      ...shorthands.borderRadius(tokens.borderRadiusSmall),
      ...shorthands.padding("1px", "5px"),
    },
    "& pre": {
      backgroundColor: tokens.colorNeutralBackground3,
      ...shorthands.borderRadius(tokens.borderRadiusMedium),
      ...shorthands.padding("12px", "14px"),
      overflowX: "auto",
      maxWidth: "100%",
    },
    "& pre code": {
      backgroundColor: "transparent",
      ...shorthands.padding("0", "0"),
    },
    "& table": {
      borderCollapse: "collapse",
      display: "block",
      overflowX: "auto",
      maxWidth: "100%",
    },
    "& th, & td": {
      ...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
      ...shorthands.padding("6px", "10px"),
      textAlign: "left",
    },
    "& a": {
      color: tokens.colorBrandForeground1,
    },
    "& figure": { margin: "1.2em 0", maxWidth: "100%" },
    "& img": {
      maxWidth: "100%",
      height: "auto",
      ...shorthands.borderRadius(tokens.borderRadiusMedium),
      ...shorthands.border("1px", "solid", tokens.colorNeutralStroke2),
    },
  },
  foot: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "36px",
    ...shorthands.padding("16px", "0", "0"),
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
});
